chiave_core:
    resource: "@ChiaveCoreBundle/Controller/"
    type:     annotation
    prefix:   /

chiave_es:
    resource: "@ChiaveErepublikScrobblerBundle/Controller/"
    type:     annotation
    prefix:   /

chiave_mu:
    resource: "@ChiaveMilitaryUnitBundle/Controller/"
    type:     annotation
    prefix:   /

chiave_stats:
    resource: "@ChiaveStatsBundle/Controller/"
    type:     annotation
    prefix:   /

chiave_user:
    resource: "@ChiaveUserBundle/Controller/"
    type:     annotation
    prefix:   /

chiave_static:
    resource: "@ChiaveStaticBundle/Controller/"
    type:     annotation
    prefix:   /