services:
    date_time:
        class:  Chiave\StatsBundle\Service\DateTimeService
        calls:
            - [setContainer, [@service_container]]

    citizen_stats:
        class:  Chiave\StatsBundle\Service\CitizenStatsService
        calls:
            - [setContainer, [@service_container]]
